using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace Sdcb.GgufWeights.Packer;

/// <summary>C# source for each part assembly. Manifests are literals — no reflection, AOT/trim safe.</summary>
internal static class SourceGenerator
{
    public static string Generate(PackPlan plan, PartPlan part)
    {
        StringBuilder sb = new();
        NuGet.Versioning.NuGetVersion v = plan.Version;
        string numeric = $"{v.Major}.{v.Minor}.{v.Patch}.0";
        sb.AppendLine("// <auto-generated/> by Sdcb.GgufWeights.Packer");
        sb.AppendLine("using Sdcb.GgufWeights;");
        sb.AppendLine();
        sb.AppendLine($"[assembly: System.Reflection.AssemblyVersion({Lit(numeric)})]");
        sb.AppendLine($"[assembly: System.Reflection.AssemblyFileVersion({Lit(numeric)})]");
        sb.AppendLine($"[assembly: System.Reflection.AssemblyInformationalVersion({Lit(v.ToNormalizedString())})]");
        sb.AppendLine($"[assembly: System.Reflection.AssemblyTitle({Lit(part.PackageId)})]");
        sb.AppendLine();
        sb.AppendLine($"namespace {plan.Namespace}");
        sb.AppendLine("{");
        AppendPart(sb, plan, part);
        if (part.IsEntry)
        {
            sb.AppendLine();
            AppendWeights(sb, plan);
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendPart(StringBuilder sb, PackPlan plan, PartPlan p)
    {
        sb.AppendLine($"    /// <summary>Segment {p.Index + 1}/{plan.Parts.Length} of {Xml(plan.FileName)}.</summary>");
        sb.AppendLine($"    public static class {p.ClassName}");
        sb.AppendLine("    {");
        sb.AppendLine($"        public static IModelWeightSegment Segment {{ get; }} = new EmbeddedWeightSegment(");
        sb.AppendLine($"            typeof({p.ClassName}).Assembly,");
        sb.AppendLine($"            {Lit(p.ResourceName)},");
        sb.AppendLine("            new ModelSegmentManifest");
        sb.AppendLine("            {");
        sb.AppendLine($"                ModelId = {Lit(plan.ModelId)},");
        sb.AppendLine($"                File = {Lit(plan.FileName)},");
        sb.AppendLine($"                Index = {p.Index},");
        sb.AppendLine($"                Count = {plan.Parts.Length},");
        sb.AppendLine($"                Offset = {Long(p.Offset)},");
        sb.AppendLine($"                Length = {Long(p.Length)},");
        sb.AppendLine($"                Sha256 = {Lit(p.Sha256)},");
        sb.AppendLine("            });");
        sb.AppendLine("    }");
    }

    private static void AppendWeights(StringBuilder sb, PackPlan plan)
    {
        sb.AppendLine($"    /// <summary>{Xml(plan.FileName)} stitched from {plan.Parts.Length} embedded segment(s).</summary>");
        sb.AppendLine("    public static class Weights");
        sb.AppendLine("    {");
        sb.AppendLine($"        public const string ModelId = {Lit(plan.ModelId)};");
        sb.AppendLine($"        public const string FileName = {Lit(plan.FileName)};");
        sb.AppendLine($"        public const long Length = {Long(plan.FileLength)};");
        sb.AppendLine("        /// <summary>SHA-256 (hex, lowercase) of the whole stitched file.</summary>");
        sb.AppendLine($"        public const string Sha256 = {Lit(plan.FileSha256)};");
        sb.AppendLine();
        sb.AppendLine("        public static IModelWeightSegment[] Segments() => new IModelWeightSegment[]");
        sb.AppendLine("        {");
        foreach (PartPlan p in plan.Parts)
            sb.AppendLine($"            {p.ClassName}.Segment,");
        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>Opens the stitched, seekable, read-only GGUF stream.</summary>");
        sb.AppendLine("        public static SegmentStream Model() => SegmentStream.Join(Segments());");
        sb.AppendLine("    }");
    }

    private static string Lit(string s) => SymbolDisplay.FormatLiteral(s, quote: true);
    private static string Long(long n) => n.ToString(CultureInfo.InvariantCulture) + "L";
    private static string Xml(string s) => System.Security.SecurityElement.Escape(s);
}
